dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8

language: cpp

script:
  - mkdir build
  - cd build
  - CC=gcc-8 CXX=g++-8 cmake ..
  - make
  - make test
