dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

language: cpp
compiler:
  - gcc

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test
